stages:
  data_ingestion:
    cmd: python -m src.components.data_ingestion
    deps:
    - src\components\data_ingestion.py
    outs:
    - Artifacts\data_ingestion\ingested\test.csv
    - Artifacts\data_ingestion\ingested\train.csv
    - data\raw\latest\phisingData

  data_validation:
    cmd: python -m src.components.data_validation
    deps:
    - Artifacts\data_ingestion\ingested\test.csv
    - Artifacts\data_ingestion\ingested\train.csv
    - src\components\data_validation.py
    outs:
    - Artifacts\data_validation\drift_report\report.yaml
