stages:
  data_ingestion:
    cmd: python -m src.components.data_ingestion
    deps:
    - src\components\data_ingestion.py
    outs:
    - Artifacts\data_ingestion\ingested\test.csv
    - Artifacts\data_ingestion\ingested\train.csv
    - data\raw\latest\phisingData

  data_validation:
    cmd: python -m src.components.data_validation
    deps:
    - Artifacts\data_ingestion\ingested\test.csv
    - Artifacts\data_ingestion\ingested\train.csv
    - src\components\data_validation.py
    outs:
    - Artifacts\data_validation\drift_report\report.yaml

  data_transformation:
    cmd: python -m src.components.data_transformation
    deps:
    - src\components\data_transformation.py
    - Artifacts\data_validation\drift_report\report.yaml
    outs:
    - Artifacts\data_transformation\transformed\test.npy
    - Artifacts\data_transformation\transformed\train.npy

  model_training:
    cmd: python -m src.components.model_training
    deps:
    - src\components\data_transformation.py
    - Artifacts\data_transformation\transformed\test.npy
    - Artifacts\data_transformation\transformed\train.npy
    outs:
    - Artifacts\model_trainer\trained_model\model.pkl
